### ISSUE TITLE
Save file should not check for existence

### ISSUE THREAD

**Issue by mvp-2003** [mvp-2003/fformat#10]
We already have a _button_ to choose the _folder_ in which the _image_ is supposed to be _saved_. This **eliminates** the need to check if the folder already _exists_ or _not_.

All we need to do is make the file get saved in the folder selected. The file will be the text inside the new_file_label widget. We need not check for any formats here since the file will be computer generated.

We just need to implement the save button.

Also the function **returns** a value to the terminal. We need to tell the user about it who is using the GUI and has no access to terminal. Please add the return statement (obviously if it a string) into widgets on the GUI.

**Comment by ZayanRashid295** [comment]
check

**Comment by ZayanRashid295** [comment]
Have you checked it?

**Comment by mvp-2003** [comment]
yes
