### ISSUE TITLE
Implement the Save file function

### ISSUE THREAD

**Issue by mvp-2003** [mvp-2003/fformat#3]
The save button is supposed to save the file int he folder chosen using the "Choose folder". Please update the command, and implement the function in the respective file.

**Comment by ZayanRashid295** [comment]
check
further more i already have the logics implemented available for the conversions

**Comment by ZayanRashid295** [comment]
should i change that too?

**Comment by mvp-2003** [comment]
I don't see the logics for the conversions. We need not bother about that for now. We can work on that very soon. First let us complete the frontend.
